repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
        files: \.rs$
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.6.1
    hooks:
      - id: validate_manifest
      # - id: end-of-file-fixer
      #   name: end-of-file-fixer
        # description: Ensures files end with a newline
        # entry: end-of-file-fixer
        # language: python
        # exclude: \.gitmodules$
