[package]
name = "quantixar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etcd = "0.9.0"
faiss = { version = "0.12.1"}
lazy_static = "1.4.0"
parking_lot = { version = "0.12.1", features = ["serde"] }
rayon = "1.8.1"
rocksdb = "0.21.0"
thiserror = "1.0.56"
tokio = { version = "1.36.0", features = ["rt-multi-thread"] }
