comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
wrap_comments = true
edition = "2021"
brace_style = "AlwaysNextLine"
chain_width = 80
max_width = 100
