comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Horizontal"
wrap_comments = true
edition = "2021"
chain_width = 80
max_width = 100
tab_spaces = 2
