name: "Quantixar Build And Test"

on: [push]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: setup | checkout
        uses: actions/checkout@v2
      - name: setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: setup | Compile
        run: cargo check
  test:
    name: tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        rust:
          - stable
        dir:
          - lib/segment
          - lib/common
    runs-on: ${{ matrix.os }}
    needs: [compile]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Build | Compile
        working-directory: ${{ matrix.dir }}
        run: cargo test
